### ISSUE TITLE
Is there anyway to make this run, without network connectivity?

### ISSUE THREAD

**Issue by davidhonsvick** [wireload/screenly-ose#276] opened 2015-03-27 21:45 UTC
Hello,
I have this on a raspberry pi and it works like a dream. I do have a couple locations I would like to post a sign that I can not get connectivity to. The player just sits with a black screen waiting. The second you plug in a cable it grabs an IP and comes to life.

When I look at the logs for the duration the sign was asleep it says:

Playlist is empty. Sleeping for 5 seconds
Playlist is empty. Sleeping for 5 seconds
Playlist is empty. Sleeping for 5 seconds
Playlist is empty. Sleeping for 5 seconds
Playlist is empty. Sleeping for 5 seconds

This leads me to believe that the system relies on the eth0 IP either start a service and bind the data server OR the scripts use the eth0 interface IP in the path to get to the database.
(If I had to guess) 

I am thinking static the IP might help, however some linux distros ignore the static IP of an interface if it is offline, Possibly force the server to bind to 127.0.0.1.

Just curious if anyone is doing this.

**Comment by vpetersson** [comment] 2015-03-28 14:22
Closing. Duplicate of #247.

**Closed by vpetersson** 2015-03-28 14:22 UTC
