### ISSUE TITLE
Screenly OSE Active Asset Not Displaying

### ISSUE THREAD

**Issue by rono711** [wireload/screenly-ose#546] opened 2017-02-23 04:08 UTC
Dear All,
I am 100% new in Screenly. I added asset and turned it ON. It's under Active Status. However, nothing is on my big screen? Any advice or tip would be much appreciated. 
![test](https://cloud.githubusercontent.com/assets/25971546/23244537/1e9d1ffe-f9da-11e6-9610-0c84ddf3e8f4.png)

**Comment by zaphod2010** [comment] 2017-02-23 09:54
I had the same issue a while back., Turned out that the Raspberry's clock was way off.
I added this as a root cronjob:

`@reboot /bin/sleep 30 ; /bin/date -s "$(/usr/bin/curl -s --head http://google.com | /bin/grep ^Date: | /bin/sed 's/Date: //g')"`

**Comment by vpetersson** [comment] 2017-04-05 10:13
Just to chime in here. Normally, the `ntp` service should be responsible for setting the clock. As such, the root cause is likely either that NTP service is incorrectly configured, or NTP is blocked by the firewall. Since the Raspberry Pi doesn't have any RTC, NTP is required.

If you are unable to use NTP, I suggest you look into [HTP](http://www.vervest.org/htp/). I will close this issue as this is not related to Screenly per se, but rather a network issue.

**Closed by vpetersson** 2017-04-05 10:13 UTC
Labels: bug
