### ISSUE TITLE
Daily programmation of a asset

### ISSUE THREAD

**Issue by Mugiwara75** [wireload/screenly-ose#262] opened 2015-02-12 15:35 UTC
Hi,

I want to know if it's possible to implemente a daily programmation.

For exemple, put this web page every day at 5pm.

It is not a real issue but a "nice to have", I hope I'm on the good place to request this new option.

Thanks

**Comment by Mugiwara75** [comment] 2015-02-12 15:38
Maybe this issue is the same request ? https://github.com/wireload/screenly-ose/issues/153 ???

**Comment by vpetersson** [comment] 2015-02-12 17:32
Yes, this is a duplicate of #153. Closing.

**Closed by vpetersson** 2015-02-12 17:32 UTC
