### ISSUE TITLE
Screenly runs for approximately 4-5 hrs - display goes dark - cannot access web admin

### ISSUE THREAD

**Issue by chadmaag** [wireload/screenly-ose#242] opened 2014-12-01 19:05 UTC
Greetings All

Apologies in advance if I've overlooked any matters with regards to formatting. This is my first time posting in GitHub.

We've been running Screenly in an internal beta test to push digital signage for our multi-site church. The software has been exactly what we're looking for, and have been thrilled with how it works.

Everything has been running solid for a few months until this past week. We find we're now getting approximately 4-5 hrs of uptime with Screenly. Afterwards, the screen goes dark, and we're no longer able to access the web admin panel. I am able to SSH to the device using putty. A reboot brings everything back online for another 4-5 hrs. Lather. Rinse. Repeat.

We're running the current OSE build, on a Raspberry Pi Model B, using an official Raspberry Pi power supply. I pulled the device from the location it was installed and hooked it to a different power circuit as well as a new monitor to verify we weren't having power issues or screen issues causing the problem.

Seeing the recommended course of action described by @vpetersson in a [previously closed thread](https://github.com/wireload/screenly-ose/issues/219)

I ran the following command until the device crashed

```$ tail -f /var/log/syslog /tmp/screenly*.log```

Here's the results leading up to, at the point of, and after the crash

```
Mon, 01 Dec 2014 17:53:31 Showing asset December Welcome (image)
Mon, 01 Dec 2014 17:53:31 Sleeping for 8
Mon, 01 Dec 2014 17:53:39 Showing asset December Welcome Book (image)
Mon, 01 Dec 2014 17:53:40 Sleeping for 8
Mon, 01 Dec 2014 17:53:48 Showing asset December Prayer (image)
Mon, 01 Dec 2014 17:53:49 Sleeping for 8
Mon, 01 Dec 2014 17:53:57 Showing asset December Connections (image)
Mon, 01 Dec 2014 17:53:58 Sleeping for 8
Mon, 01 Dec 2014 17:54:06 Showing asset December Groups (image)
Mon, 01 Dec 2014 17:54:06 Sleeping for 8
Mon, 01 Dec 2014 17:54:15 Showing asset Wornall Wednesdays (image)
Mon, 01 Dec 2014 17:54:15 Sleeping for 8
Mon, 01 Dec 2014 17:55:00 Showing asset Birthday Party for Jesus (image)
Mon, 01 Dec 2014 17:55:15 Sleeping for 8
Mon, 01 Dec 2014 17:55:24 Showing asset Angel Tree (image)
Mon, 01 Dec 2014 17:55:24 Sleeping for 8
Mon, 01 Dec 2014 17:55:32 Showing asset Poinsettia Order Form (image)
Mon, 01 Dec 2014 17:55:33 Sleeping for 8
Mon, 01 Dec 2014 17:55:41 Showing asset WTTM Promo (image)
Mon, 01 Dec 2014 17:55:41 browser found dead, restarting
Mon, 01 Dec 2014 17:55:41 Loading browser...

== /tmp/screenly_xloader.log ==
Traceback (most recent call last):
  File "/home/pi/screenly/viewer.py", line 364, in <module>
    main()
  File "/home/pi/screenly/viewer.py", line 360, in main
    asset_loop(scheduler)
  File "/home/pi/screenly/viewer.py", line 298, in asset_loop
    view_image(uri)
  File "/home/pi/screenly/viewer.py", line 181, in view_image
    browser_send('js window.setimg("{0}")'.format(uri), cb=lambda b: 'COMMAND_EXECUTED' in b and 'setimg' in b)
  File "/home/pi/screenly/viewer.py", line 160, in browser_send
    load_browser()
  File "/home/pi/screenly/viewer.py", line 131, in load_browser
    if browser:
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 334, in __len__
    return len(str(self))
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 370, in __str__
    else: return unicode(self).encode(self.call_args["encoding"])
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 373, in __unicode__
    if self.process and self.stdout:
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 316, in stdout
    self.wait()
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 295, in wait
    self._handle_exit_code(self.process.wait())
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 309, in _handle_exit_code
    self.process.stderr
sh.SignalException_11:

  RAN: '/usr/bin/uzbl-browser --config=- --uri=file:///tmp/screenly_html/black_page.html --print-events'

  STDOUT:
EVENT [2426] INSTANCE_START 2426
EVENT [2426] BUILTINS 'back forward scroll reload reload_ign_cache stop zoom_in zoom_out toggle_zoom_type uri js script toggle_status spawn sync_spawn sync_spawn_exec sh sync_sh exit search search_reverse search_clear dehilight set toggle dump_config dump_config_as_events chain print event request menu_add menu_link_add menu_image_add menu_editable_add menu_separator menu_link_separator menu_image_separator menu_editable_separator menu_remove menu_link_remove menu_image_remove menu_editable_remove hardcopy include show_inspector add_cookie delete_cookie clear_cookies download '
EVENT [2426] VARIABLE_SET status_format str '<b>@[@TITLE]@</b> - @[@uri]@ - <span foreground="#bbb">@NAME</span>'
EVENT [2426] VARIA... (291421 more, please see e.stdout)

  STDERR:

Cleaning up...
Cleaning up...
Cleaning up...
Cleaning up...
Cleaning up...
Cleaning up...
```

"Cleaning up" continued on in what is to be assumed perpetuity. 

I suspect we have a bad SD card. Card isn't labeled to indicate if it is a SLC, MLC, or TLC card. Can anyone confirm with what I've posted here?

**Comment by vpetersson** [comment] 2015-10-05 10:43
@Cyberprog / @chadmaag Are you still able to reproduce this?

**Comment by smartye** [comment] 2015-10-06 14:19
Hi Viktor,
i'm also facing the same problem.I have deployed 8 screens and one of the works for about 4 hours and then black screen + Cleaning up.. continuous message.

Looking forward to hear from you.

Regards

**Comment by vpetersson** [comment] 2015-10-06 14:41
@smartye can you provide exact steps to reproduce this?

**Comment by smartye** [comment] 2015-10-06 14:57
Hi Viktor,
until now i haven't understood the reason why this happens. Screenly it's running 5 images in loop

Tue, 06 Oct 2015 15:53:13 Showing asset cinema COVER.png (image)
Tue, 06 Oct 2015 15:53:13 Sleeping for 3
Tue, 06 Oct 2015 15:53:16 Showing asset Brevemente-black-mass.jpg (image)
Tue, 06 Oct 2015 15:53:16 Sleeping for 30
Tue, 06 Oct 2015 15:53:46 Showing asset Brevemente-crimason-peak.jpg (image)
Tue, 06 Oct 2015 15:53:46 Sleeping for 30
Tue, 06 Oct 2015 15:54:17 Showing asset Brevemente-pan.jpg (image)
Tue, 06 Oct 2015 15:54:17 Sleeping for 30
Tue, 06 Oct 2015 15:54:47 Showing asset Brevemente-the-walk.jpg (image)
Tue, 06 Oct 2015 15:54:47 Sleeping for 30
Tue, 06 Oct 2015 15:55:17 Generating asset-list...

After a few hours screenly stops and the solution it's to sudo reboot the raspberry
I can send you more information, please be so kind to explain me where to start

Regards

**Comment by vpetersson** [comment] 2015-10-06 15:19
@smartye Please run the following:

```
tar cvfz ~/debug.tgz ~/screenly ~/screenly_assets ~/.screenly /var/log
```

That should create a file called `debug.tgz` in your home dir. Please attach this file here

**Comment by smartye** [comment] 2015-10-07 15:06
root@screenly:/tmp# tar cvfz ~/debug.tgz ~/screenly ~/screenly_assets ~/.screenly /var/log
tar: Removing leading `/' from member names
tar: /root/screenly: Cannot stat: No such file or directory
tar: /root/screenly_assets: Cannot stat: No such file or directory
tar: /root/.screenly: Cannot stat: No such file or directory
/var/log/
/var/log/apt/
/var/log/apt/term.log
/var/log/apt/history.log
/var/log/dmesg.0
/var/log/supervisor/
/var/log/supervisor/supervisord.log
/var/log/supervisor/screenly-access.log
/var/log/debug
/var/log/fsck/
/var/log/fsck/checkfs
/var/log/fsck/checkroot
/var/log/ConsoleKit/
/var/log/ConsoleKit/history
/var/log/Xorg.0.log.old
/var/log/auth.log
/var/log/mail.info
/var/log/fail2ban.log
/var/log/lpr.log
/var/log/dmesg.3.gz
/var/log/ntpstats/
/var/log/watchdog/
/var/log/messages
/var/log/syslog
/var/log/ufw.log
/var/log/lightdm/
/var/log/lightdm/lightdm.log
/var/log/lightdm/x-0.log
/var/log/news/
/var/log/news/news.err
/var/log/news/news.notice
/var/log/news/news.crit
/var/log/user.log
/var/log/dpkg.log
/var/log/mail.log
/var/log/Xorg.0.log
/var/log/kern.log
/var/log/mail.err
/var/log/dmesg
/var/log/dmesg.2.gz
/var/log/dmesg.1.gz
/var/log/lastlog
/var/log/mail.warn
/var/log/dmesg.4.gz
/var/log/daemon.log
tar: Exiting with failure status due to previous errors

**Comment by vpetersson** [comment] 2015-10-07 15:08
Ah, i didn't expect you to be logged in as root. 

Do this first:

```
sudo su - pi
```

**Comment by smartye** [comment] 2015-10-07 15:15
Hi Viktor,
i've tried to run the command again but i receive the following message

"tar: Exiting with failure status due to previous errors"

i think it's because of this during tar:
tar: /var/log/fail2ban.log: Cannot open: Permission denied
tar: /var/log/lightdm: Cannot open: Permission denied

Thank you

**Comment by vpetersson** [comment] 2015-10-07 15:17
Ok, run this as root instead then:

```
tar cvfz ~/debug.tgz /home/pi/screenly /home/pi/screenly_assets /home/ip/.screenly /var/log
```

**Comment by smartye** [comment] 2015-10-07 16:04
In the meanwhile i had to restart the raspberry to have the system running.

I have run the command with the system OK. The .tzg result it's available at
http://we.tl/ugCkGqZvWy
Next time i have the system down i will run the command again. This way we can compare files

**Comment by vpetersson** [comment] 2015-10-08 09:59
Thanks. @over64 will take a look and see if he can reproduce the issue.

**Comment by over64** [comment] 2015-10-08 10:39
Maybe it's possible to dump image from SD card?

**Comment by smartye** [comment] 2015-10-08 10:42
Hi @over64 , it's not possible to copy the SD card because the site it's 400kms far

**Comment by vpetersson** [comment] 2015-10-08 11:01
@over64 the tgz file above should include all the data needed to reproduce this.

**Comment by over64** [comment] 2015-10-15 06:32
Tested configuration provided by @smartye. Works fine, without any crashes. Also I analyzed system logs included in archive.
#### 20 August 
* 11.17: Boot
* 14.14: mmc0: Timeout waiting for hardware interrupt cmd 18
* 14.07: OOM kills ntpd
* 14.37: OOM klls uzbl-core
* reboot
* 21.17: Boot
* 00.04: OOM kills X
* 00.04: OOM kills uzbl-core
* 01.14: mmc0
* 02.17: reboot

#### 21 August
* 11.18: kill uzbl-core
* 14.33: mmc
* 15.11: mmc

21, 22 - mmc
23 - OOM kills uzbl-core
#### 24-28 August
```
Aug 25 11:03:04 screenly kernel: [ 5400.834215] INFO: task kworker/u2:1:2743 blocked for more than 120 seconds.
Aug 25 11:03:06 screenly kernel: [ 5400.834279]       Not tainted 3.12.25+ #700
Aug 25 11:03:07 screenly kernel: [ 5400.834292] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Aug 25 11:03:08 screenly kernel: [ 5400.834313] kworker/u2:1    D c043e56c     0  2743      2 0x00000000
Aug 25 11:03:08 screenly kernel: [ 5400.834397] Workqueue: kmmcd mmc_rescan
Aug 25 11:03:08 screenly kernel: [ 5400.834478] [<c043e56c>] (__schedule+0x2a0/0x5ac) from [<c033b258>] (__mmc_claim_host+0xb4/0x24c)
Aug 25 11:03:09 screenly kernel: [ 5400.834532] [<c033b258>] (__mmc_claim_host+0xb4/0x24c) from [<c0341c28>] (mmc_sd_detect+0x1c/0x70)
Aug 25 11:03:09 screenly kernel: [ 5400.834571] [<c0341c28>] (mmc_sd_detect+0x1c/0x70) from [<c033d6f8>] (mmc_rescan+0xcc/0x440)
Aug 25 11:03:09 screenly kernel: [ 5400.834616] [<c033d6f8>] (mmc_rescan+0xcc/0x440) from [<c00353dc>] (process_one_work+0x118/0x378)
Aug 25 11:03:09 screenly kernel: [ 5400.834652] [<c00353dc>] (process_one_work+0x118/0x378) from [<c003631c>] (worker_thread+0x140/0x450)
Aug 25 11:03:09 screenly kernel: [ 5400.834686] [<c003631c>] (worker_thread+0x140/0x450) from [<c003c03c>] (kthread+0xa4/0xb0)
Aug 25 11:03:09 screenly kernel: [ 5400.834743] [<c003c03c>] (kthread+0xa4/0xb0) from [<c000df58>] (ret_from_fork+0x14/0x3c)
Aug 25 11:31:04 screenly kernel: [ 7080.860715] INFO: task kworker/u2:2:2810 blocked for more than 120 seconds.
Aug 25 11:31:06 screenly kernel: [ 7080.860785]       Not tainted 3.12.25+ #700
Aug 25 11:31:07 screenly kernel: [ 7080.860800] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
```

Also found some broadcast blocked by firewall (UFW)

There is nothing criminal in logs after 28 August. It seems that works fine.
This machine uses outstanding kernel. System update can be perfomed. Possibly it may solve problems

**Comment by vpetersson** [comment] 2015-10-15 16:03
Closing out issue as we are unable to reproduce the issue.

**Closed by vpetersson** 2015-10-15 16:03 UTC

**Comment by smartye** [comment] 2015-10-29 00:23
thank you @vpetersson and @over64 
Since last post i haven't had any issues with this screen.

**Comment by vpetersson** [comment] 2015-10-29 09:26
Thanks, @smartye.

**Comment by smartye** [comment] 2015-12-16 15:12
Hi @vpetersson and @over64 
The problem i mentioned earlier started again.
See below a link to download the debug file
http://we.tl/WEDyip4r5d
Looking forwared to hear from you

**Comment by vpetersson** [comment] 2015-12-16 16:56
@smartye Could you provide some details on what changed between your previous comment when it worked until it broke? Were there content/scheduling changes?

**Comment by smartye** [comment] 2015-12-17 10:02
@vpetersson contents and their schedule are changed every week

**Comment by vpetersson** [comment] 2015-12-17 10:07
@smartye Right, but the point being that it is likely something in the particular playlist configuration.

I've extracted the playlist from the dump. Could you take a look at this @over64 and see if you can reproduce it.

Here's a copy of the playlist for the records:

```
$ echo 'SELECT * FROM assets;' | sqlite3 screenly.db
72f1ec88d0b94cecbdcea76e76f70a28|cinema NOS.png|/home/pi/screenly_assets/72f1ec88d0b94cecbdcea76e76f70a28||2015-08-01 06:00:00|2016-08-31 00:00:00|3|image|1|0|0
28a15b837d054bf29684bf713edd8a49|Brevemente-creed.jpg|/home/pi/screenly_assets/28a15b837d054bf29684bf713edd8a49||2015-10-21 22:54:00|2015-10-29 23:54:00|30|image|1||1
4a6e9e61e7ba4de2b60a6faf4c51bfdc|Brevemente-good-dino.jpg|/home/pi/screenly_assets/4a6e9e61e7ba4de2b60a6faf4c51bfdc||2015-10-21 22:54:00|2015-10-29 23:54:00|30|image|1||2
a668e30e13cb4fd2b50e8769bb1fc237|Brevemente-knock-knock.jpg|/home/pi/screenly_assets/a668e30e13cb4fd2b50e8769bb1fc237||2015-10-21 22:54:00|2015-10-29 23:54:00|30|image|1||3
c92433c29fad4180902afe2986055228|Brevemente-krampus.jpg|/home/pi/screenly_assets/c92433c29fad4180902afe2986055228||2015-10-21 22:54:00|2015-10-29 23:54:00|30|image|1||4
23eec0a781634ce6840d371f98d9eeb3|Brevemente-os-sufragistas.jpg|/home/pi/screenly_assets/23eec0a781634ce6840d371f98d9eeb3||2015-10-21 22:55:00|2015-10-29 23:55:00|30|image|1||5
6546f4457ec946409189740dc96b5f6b|Brevemente-song-one.jpg|/home/pi/screenly_assets/6546f4457ec946409189740dc96b5f6b||2015-10-21 22:55:00|2015-10-29 23:55:00|30|image|1||6
4dcff01c2cb3474fa5491222e183cd25|Brevemente-starwars.jpg|/home/pi/screenly_assets/4dcff01c2cb3474fa5491222e183cd25||2015-10-21 22:55:00|2015-10-30 23:55:00|30|image|1||7
147648927056456886ff8a81861bb866|2015 10 21 NOSCinemas Meios CR7_1080x1920.png|/home/pi/screenly_assets/147648927056456886ff8a81861bb866||2015-10-23 17:50:00|2015-11-05 18:50:00|30|image|1||8
```

**Comment by over64** [comment] 2015-12-17 10:35
I have tried screenly/ conf/ assets from archive and got
![image](https://cloud.githubusercontent.com/assets/2621273/11867580/d7b84a66-a4d3-11e5-88eb-c27b76163271.png)

**Comment by vpetersson** [comment] 2015-12-17 10:42
@over64 did you try that on an actual Pi or locally?

Please try simply copying in the entire archive in the debug archive to a Pi and see what happens.

**Comment by over64** [comment] 2015-12-17 11:00
@vpetersson, the same on real device)

**Comment by vpetersson** [comment] 2015-12-17 11:04
Right, but as per @smartye initial description, it can take 4-5 hours to reproduce.

**Comment by over64** [comment] 2015-12-17 11:06
@vpetersson, hm... ok, will try to make it
