### ISSUE TITLE
Uploads

### ISSUE THREAD

**Issue by rsenio** [wireload/screenly-ose#171] opened 2013-11-25 21:54 UTC
Having an issue uploading an H.264 MP4. File size is 1.48GB. 8GB card and it has close to 3.1GB free. The upload progress bar goes all the way and I would think should successfully create the asset for me. However, the progress bar does not go away, and if I watch the space on the screenly SD Card using df -h I can see it literally chew away all the space until there is none left. Then it errors and states I have to refresh the webpage and try the upload again.

**Comment by lenny76** [comment] 2015-03-11 12:52
+1

**Comment by markjwill** [comment] 2015-06-22 12:23
+1 

On my pi Screenly system info shows 43Gb available and I cannot upload a 28Gb video.    I get a message that says it is "full".  Is it trying to encode my video?  Is there an alternate method of uploading video?

**Comment by vpetersson** [comment] 2015-06-22 12:26
@markjwill The upload aside, I don't even know if the Pi can play a 28GB video. That's *massive*. Keep in mind what kind of hardware you're dealing with here.

**Comment by richardplenty** [comment] 2015-06-22 14:51
This must be a really old question I asked.  With the P2 model I can play pretty big data rates.  One other thing now appears is that in random playback mode certain videos play much more often than others.  It does not appear random.  Is there a problem with the software?  I have about 60 clips and  several play many times more often than the others. 

Date: Mon, 22 Jun 2015 05:26:05 -0700

**Comment by vpetersson** [comment] 2015-06-22 15:01
So Screenly is really just calling on `omxplayer` for videos, so there isn't anything fancy there really. That said, just buffering a file of that size will likely take a minute or so before the playback starts. I would strongly recommend smaller videos for anything production.

**Comment by vpetersson** [comment] 2015-09-23 16:16
Duplicate of #123.

**Closed by vpetersson** 2015-09-23 16:16 UTC
