### ISSUE TITLE
Head request are rejected by Kibana4

### ISSUE THREAD

**Issue by xhujerr** [wireload/screenly-ose#363] opened 2016-03-01 16:43 UTC
We are using Screenly to display dashboards in Kibana4. The issue is that Kibana4 rejects head request with 403 and it is not easily configurable to start accepting the head requests.

I did workaround my Screenly instance as folllows:
utils.py line 99:
`obj = requests.head(...)` -> `obj = requests.get(...)`

Can this behavior be configurable?

**Comment by vpetersson** [comment] 2016-03-01 16:51
Duplicate of #249. Tl;dr: generally speaking it would be better to fix this upstream (i.e. in Kabana) as it breaches the HTTP RFCs by returning a different response for GET vs. HEAD.

**Closed by vpetersson** 2016-03-01 16:51 UTC
