### ISSUE TITLE
Edit (image) asset makes it unusable

### ISSUE THREAD

**Issue by ComputerSmiths** [wireload/screenly-ose#105] opened 2013-03-22 16:24 UTC
I've got some images served from my LAN, and I attempted to turn on caching to see if it made the inter-image delay more predictable, but now I can't display them at all.

When you edit an asset that's in use, it moves from the Active Assets list to the Inactive Assets list, but the ON/OFF switch is still set to ON (but it doesn't actually display in the rotation).  Turning it on and off doesn't do anything, rebooting doesn't help, turning it off and rebooting doesn't help (you can turn it ON and OFF, but it stays in the Inactive list.

Deleting them and re-creating them seems to work, but that's a lot of work...
![ScreenlyOnButNotActive](https://f.cloud.github.com/assets/1817190/291682/f64e519a-930c-11e2-9992-609ccb1e27b0.jpg)

**Comment by vpetersson** [comment] 2015-10-05 07:39
Closing out as a duplicate of #228.

**Closed by vpetersson** 2015-10-05 07:39 UTC
