### ISSUE TITLE
 "Schedule Overview" title

### ISSUE THREAD

**Issue by thefyfy** [wireload/screenly-ose#485] opened 2016-09-01 15:29 UTC
Hi,
Is it possible to have a text box in "Settings" to change the default title "Schedule Overview" ? 
When we have different screens with screenly, I think it would be great if we can identitfy quickly which screen you are changing with a custom title.
What do you think about it?
In any case, thanks for your amazing job!

**Comment by vpetersson** [comment] 2016-09-02 13:28
> In any case, thanks for your amazing job!

Thank you. 

Closing out as this is a duplicate of #349.

**Closed by vpetersson** 2016-09-02 13:28 UTC
