### ISSUE TITLE
Workaround to save Displaypower using a cronjob to disable HDMI Interface

### ISSUE THREAD

**Issue by windegg** [wireload/screenly-ose#216] opened 2014-08-26 14:10 UTC
a view weeks ago, i told our 32" display uses 50W even, the screenly shows a blank screen. I found some settings to disable the HDMI Interface of my raspberry. 

Here my scripts and a sample cronjob:

cat cron.tab
# HDMI off at 6:00pm
* 18  *  *   *   /home/pi/m-off.sh
# HDMI on every working day
* 8  *  *   1-5   /home/pi/m-on.sh
*************************************************************

cat m-off.sh
#!/bin/bash
/usr/bin/tvservice -o

cat m-on.sh
#!/bin/bash
sudo /usr/bin/tvservice -p
sleep 1
sudo /bin/chvt 6
sleep 1
sudo /bin/chvt 7

**Comment by vpetersson** [comment] 2016-04-26 10:35
Duplicate of #26.

**Closed by vpetersson** 2016-04-26 10:35 UTC
