### ISSUE TITLE
Active Asset Not Displaying

### ISSUE THREAD

**Issue by Photovor** [wireload/screenly-ose#147] opened 2013-07-09 13:19 UTC
We created different a Web Page asset to start playing at 1:00am every day, with one asset (image) that is always showing.

When we check the screen on a following day, the ever-changing assets (web pages) are never playing, but the asset that is set to be on there constantly is the only one playing.  When I log into screenly, and look at the log, it shows me that the single static image has just been playing over and over.  Then, when I go into the Schedule Overview, I I see the static and web page assets under active, and they are both listed as on.  If I click the pencil icon next to the web page asset, then just cancel out, then go check the viewer log, it shows "Generating asset-list...", and then the assets will start rotating properly.  Any clue what's happening?

**Comment by vpetersson** [comment] 2016-05-03 08:48
@Photovor / @kfuglsang Are you still able to reproduce this? Closing this issue for now. Will re-open if we have steps for reproduction.

**Closed by vpetersson** 2016-05-03 08:48 UTC

**Comment by Sofwath** [comment] 2016-05-28 10:18
I have the same issue twice

**Comment by Sofwath** [comment] 2016-05-28 10:19
I had the same issue twice

**Comment by wootyb** [comment] 2017-11-21 22:38
I am having this issue, where my assets will be frozen under the inactive section; toggling the On/Off switches accomplishes nothing. I have cleared all browser data to test and from other PC's. The only way to remedy this is to delete the asset and then create a new one, and yes I have to do this once a week, as if assets have a week long life before they become permanently deactivated. For example, if I were to leave my display unattended, after about 5 or 6 days all assets will be stuck in the ON position under inactive assets, and cannot be loaded until I create a new one.

Can't find solutions on this issue anywhere else and the photo posted by "swordfish6975" is an accurate representation of my woes. Thanks.

**Comment by swordfish6975** [comment] 2017-11-21 22:41
For me, I ran a memtest on the PI and it had a bad memory module. We swapped it to a new PI and it has been fine since.

**Comment by vpetersson** [comment] 2017-11-22 08:42
@wootyb Are you running on the latest development version?

**Comment by edocastri** [comment] 2017-12-14 11:01
I'm having the same issue.
I'm running the last dev version.
As you can see in the images, turning it off and the on again doesn't work.
The only way to fix this so far, is delete it and then add again.

When this happens, System info page shows this:

> 

Dec 14 07:53:28 rsp_contestadora python[636]: Generating asset-list...
--
Dec 14 07:53:28 rsp_contestadora python[636]: Playlist is empty. Sleeping for 5 seconds
Dec 14 07:53:33 rsp_contestadora python[636]: Generating asset-list...
Dec 14 07:53:33 rsp_contestadora python[636]: Playlist is empty. Sleeping for 5 seconds

And then when del and re-add shows this:

> 

Dec 14 07:54:03 rsp_contestadora python[636]: Playlist is empty. Sleeping for 5 seconds
--
Dec 14 07:54:08 rsp_contestadora python[636]: Playlist is empty. Sleeping for 5 seconds
Dec 14 07:54:14 rsp_contestadora python[636]: Generating asset-list...
Dec 14 07:54:14 rsp_contestadora python[636]: Playlist is empty. Sleeping for 5 seconds
Dec 14 07:54:19 rsp_contestadora python[636]: Generating asset-list...
Dec 14 07:54:19 rsp_contestadora python[636]: Showing asset Frases_Espera_Telefonica_01.mp4 (video)
Dec 14 07:54:19 rsp_contestadora python[636]: current url is file:///tmp/screenly_html/black_page.html
Dec 14 07:54:52 rsp_contestadora python[636]: Generating asset-list...
Dec 14 07:54:52 rsp_contestadora python[636]: Showing asset Frases_Espera_Telefonica_01.mp4 (video)





![captura de pantalla 2017-12-14 a la s 07 53 05](https://user-images.githubusercontent.com/19616239/33988831-63c8ce8c-e0a4-11e7-8c39-181689413da3.png)
![captura de pantalla 2017-12-14 a la s 07 53 14](https://user-images.githubusercontent.com/19616239/33988840-6a7b87c4-e0a4-11e7-9fe7-fc10b3d7defe.png)

**Comment by antonmolodykh** [comment] 2017-12-14 12:37
@wootyb @edocastri 
the most obvious possible reason is that the asset just ran out of time (note the `start` and `end` dates). please make sure that the problem is not in this and let know here
