### ISSUE TITLE
RTMP Streaming for DAUs

### ISSUE THREAD

**Issue by RaspiNewb** [wireload/screenly-ose#329] opened 2015-11-19 13:37 UTC
Hey Guys,

i just set up Screenly on my Raspi. Everything goes as well and i manually changed the Standard EndTime to 10 Years in
the future in the screenly-ose.js.

So i just read Screenly is able to playback rtmp Links via OMXplayer?

But i dont be able to set up one of these.

I just changed the accepted URL Types in the utils.py file so i could save the rtmp link in the backend but there comes
just this error

Server Error: No connection adapters were found for 'rtmp://pssimn24livefs.fplive.net/pssimn24live-live/_definst_/stream1'

where i have to configure the adapter?

**Comment by RaspiNewb** [comment] 2015-11-20 11:42
i just tried to playback a livestream the normal way without any problems

i just exectued this command via ssh on the screenly

omxplayer rtmp://pssimn24livefs.fplive.net/pssimn24live-live/_definst_/stream1

so the player overlays the screenly 

Question is, how can i put this command into the normal circle for playback within the other
pictures, videos and so on

I also tried to add a new span for "Livestream" in the views/index.haml but it doesnt appear

just anyone who could help me?

**Comment by brosserg** [comment] 2015-11-25 19:39
I was wondering if you had any luck with getting your RTMP stream working? I too would like to get this working.

**Comment by vpetersson** [comment] 2015-11-25 21:29
Added this for Sprint 3.

**Comment by vpetersson** [comment] 2016-05-03 13:31
Consolidating. Duplicate of #90.

**Closed by vpetersson** 2016-05-03 13:31 UTC
Labels: feature request
